name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make release folder
        run: |
          mkdir HM3CustomMaps
          cp manifest.json HM3CustomMaps/
          cp -R content HM3CustomMaps/content
      - name: HM3CustomMaps.framework.zip
        uses: softprops/action-gh-release@v1
        with:
          files: |
            HM3CustomMaps
